// <auto-generated />
namespace CYT.Web.DataContext.CytMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ShortDescriptionOnRecipe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShortDescriptionOnRecipe));
        
        string IMigrationMetadata.Id
        {
            get { return "201606101234221_ShortDescriptionOnRecipe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
